- hosts: all
  become: yes
  tasks:
     - apt:
         pkg:
           - ansible
           - bcc
     - shell: echo 'echo -e "\\033]1337;SetProfile=Prod\\a"' >> /home/ubuntu/.bashrc
     - shell: echo 'echo -e "\\033]1337;SetProfile=Default\\a"' >> /home/ubuntu/.bash_logout
